import type { Metadata } from "next";
import "./globals.css";
import { Inter as FontSans } from "next/font/google";
import MobileNav from "../components/MobileNav";
import DesktopNav from "../components/DesktopNav";

export const fontSans = FontSans({
  subsets: ["latin"],
  variable: "--font-sans",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className="h-full">
      <body
        className={
          "h-full bg-background font-sans antialiased " + fontSans.variable
        }
      >
        <div className="flex">
          <DesktopNav />
          <main className="flex-1">
            <MobileNav />
            {children}
          </main>
        </div>
      </body>
    </html>
  );
}
